/**
 * Custom dark theme for Monaco Editor matching CodeSync AI aesthetic.
 */

export const CODESYNC_DARK_THEME = {
  base: 'vs-dark',
  inherit: true,
  rules: [
    { token: '', foreground: 'e2e8f0', background: '0d0d14' },
    { token: 'comment', foreground: '475569', fontStyle: 'italic' },
    { token: 'comment.doc', foreground: '64748b', fontStyle: 'italic' },
    { token: 'string', foreground: '6ee7b7' },
    { token: 'string.escape', foreground: '34d399' },
    { token: 'number', foreground: 'f0abfc' },
    { token: 'number.hex', foreground: 'f0abfc' },
    { token: 'keyword', foreground: 'c084fc' },
    { token: 'keyword.control', foreground: 'c084fc' },
    { token: 'type', foreground: '67e8f9' },
    { token: 'type.identifier', foreground: '67e8f9' },
    { token: 'identifier', foreground: 'e2e8f0' },
    { token: 'function', foreground: '93c5fd' },
    { token: 'function.declaration', foreground: '93c5fd', fontStyle: 'bold' },
    { token: 'variable', foreground: 'e2e8f0' },
    { token: 'variable.parameter', foreground: 'fca5a5' },
    { token: 'constant', foreground: 'f0abfc' },
    { token: 'operator', foreground: '94a3b8' },
    { token: 'delimiter', foreground: '64748b' },
    { token: 'delimiter.bracket', foreground: '94a3b8' },
    { token: 'tag', foreground: 'f87171' },
    { token: 'tag.attribute.name', foreground: 'c084fc' },
    { token: 'attribute.name', foreground: 'c084fc' },
    { token: 'attribute.value', foreground: '6ee7b7' },
    { token: 'metatag', foreground: '94a3b8' },
    { token: 'regexp', foreground: 'fbbf24' },
    { token: 'annotation', foreground: 'fbbf24' },
    { token: 'namespace', foreground: '67e8f9' },
    { token: 'class', foreground: '67e8f9', fontStyle: 'bold' },
    { token: 'interface', foreground: '67e8f9' },
    { token: 'enum', foreground: '67e8f9' },
    { token: 'property', foreground: '93c5fd' },
  ],
  colors: {
    'editor.background': '#0d0d14',
    'editor.foreground': '#e2e8f0',
    'editor.lineHighlightBackground': '#1a1a2e',
    'editor.lineHighlightBorder': '#1e1e32',
    'editor.selectionBackground': '#3b82f633',
    'editor.selectionHighlightBackground': '#3b82f61a',
    'editor.inactiveSelectionBackground': '#3b82f61a',
    'editor.wordHighlightBackground': '#8b5cf61a',
    'editor.findMatchBackground': '#f59e0b33',
    'editor.findMatchHighlightBackground': '#f59e0b1a',
    'editorCursor.foreground': '#3b82f6',
    'editorCursor.background': '#0d0d14',
    'editorWhitespace.foreground': '#1e1e32',
    'editorIndentGuide.background': '#1a1a2e',
    'editorIndentGuide.activeBackground': '#2a2a4a',
    'editorLineNumber.foreground': '#334155',
    'editorLineNumber.activeForeground': '#64748b',
    'editorBracketMatch.background': '#3b82f61a',
    'editorBracketMatch.border': '#3b82f644',
    'editorGutter.background': '#0d0d14',
    'editorOverviewRuler.border': '#0d0d14',
    'editorWidget.background': '#12121a',
    'editorWidget.border': '#1e1e32',
    'editorSuggestWidget.background': '#12121a',
    'editorSuggestWidget.border': '#1e1e32',
    'editorSuggestWidget.foreground': '#e2e8f0',
    'editorSuggestWidget.selectedBackground': '#1a1a2e',
    'editorSuggestWidget.highlightForeground': '#3b82f6',
    'editorHoverWidget.background': '#12121a',
    'editorHoverWidget.border': '#1e1e32',
    'peekView.border': '#3b82f644',
    'peekViewEditor.background': '#0d0d14',
    'peekViewTitle.background': '#12121a',
    'peekViewResult.background': '#12121a',
    'minimap.background': '#0d0d14',
    'minimapSlider.background': '#3b82f60d',
    'minimapSlider.hoverBackground': '#3b82f61a',
    'minimapSlider.activeBackground': '#3b82f633',
    'scrollbar.shadow': '#00000066',
    'scrollbarSlider.background': '#ffffff0d',
    'scrollbarSlider.hoverBackground': '#ffffff1a',
    'scrollbarSlider.activeBackground': '#ffffff26',
    'input.background': '#12121a',
    'input.border': '#1e1e32',
    'input.foreground': '#e2e8f0',
    'input.placeholderForeground': '#475569',
    'focusBorder': '#3b82f6',
    'list.hoverBackground': '#1a1a2e',
    'list.activeSelectionBackground': '#1e1e32',
    'list.focusBackground': '#1e1e32',
    'list.highlightForeground': '#3b82f6',
  },
};

export const CODESYNC_LIGHT_THEME = {
  base: 'vs',
  inherit: true,
  rules: [
    { token: '', foreground: '0f172a', background: 'ffffff' },
    { token: 'comment', foreground: '64748b', fontStyle: 'italic' },
    { token: 'string', foreground: '059669' },
    { token: 'number', foreground: 'd946ef' },
    { token: 'keyword', foreground: '9333ea' },
    { token: 'type', foreground: '0891b2' },
    { token: 'identifier', foreground: '0f172a' },
    { token: 'function', foreground: '2563eb' },
    { token: 'variable', foreground: '0f172a' },
  ],
  colors: {
    'editor.background': '#ffffff',
    'editor.foreground': '#0f172a',
    'editor.lineHighlightBackground': '#f1f5f9',
    'editor.lineHighlightBorder': '#e2e8f0',
    'editorCursor.foreground': '#2563eb',
    'editorLineNumber.foreground': '#94a3b8',
    'editorLineNumber.activeForeground': '#475569',
    'editorIndentGuide.background': '#e2e8f0',
    'editorIndentGuide.activeBackground': '#cbd5e1',
    'editorWidget.background': '#f8fafc',
    'editorWidget.border': '#e2e8f0',
    'editorSuggestWidget.background': '#ffffff',
    'editorSuggestWidget.foreground': '#0f172a',
    'editorSuggestWidget.selectedBackground': '#f1f5f9',
    'editorHoverWidget.background': '#ffffff',
    'editorHoverWidget.border': '#e2e8f0',
    'peekViewEditor.background': '#ffffff',
    'peekViewTitle.background': '#f8fafc',
    'minimap.background': '#ffffff',
  },
};

/**
 * Register the CodeSync dark theme with Monaco.
 */
export function registerCodeSyncTheme(monaco) {
  if (!monaco) return;
  monaco.editor.defineTheme('codesync-dark', CODESYNC_DARK_THEME);
  monaco.editor.defineTheme('codesync-light', CODESYNC_LIGHT_THEME);
}
